# Numpy Tutorial by [Ali Abdelaal](https://www.linkedin.com/in/aliabdelaal/) 
### this tutorial file was made for [Pixels](https://www.facebook.com/PixelsHU/) Course (Machine Learning)
## Let's Start by installing numpy
### use the following 
sudo apt-get install python-pip  
sudo pip install numpy scipy
### now include the library
import numpy as np

In [1]:
import numpy as np

# Make a simple victors and add them together

In [2]:
a = np.array([2,3])
b = np.array([4,5])
print(a)
print(b)
c = a + b
print(c)

[2 3]
[4 5]
[6 8]


# You can do all the arthimetic operations but notice that they are element-wise 

In [3]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
# notice that a+b is the same as np.add(a,b)

[6 8]
[-2 -2]
[ 8 15]
[ 0.5  0.6]


# Making dot product on two victors 

In [5]:
print(a.dot(b))
print(np.dot(a,b))

23
23


# Let's make a matrix and multiply it by a vector !

In [7]:
myMatrix = np.array([[1,2],[3,4]])
print(myMatrix.dot(a))
# notice the result = 2*1+3*2 , 2*3+3*4

[ 8 18]


# Indexing in Numpy

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [10]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


## Boolean Indexing

In [12]:
largeNumbers = a>8
largeNumbers

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]], dtype=bool)

In [13]:
# get these elements 
a[largeNumbers]

array([ 9, 10, 11, 12])

# Sum and transposing a matrix

In [14]:
result = np.sum(a)
print(result)

78


In [16]:
# getting the transpose 
print(a)
print("-------")
print(a.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# That's it for now, feel free to search on the web for more details and information.